apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: argocd-app
 namespace: argocd
spec:
 source:
  repoURL: https://github.com/makkasbed/argo-cd.git
  targetRevision: HEAD
  path: dev
 destination:
  server: https://kubernetes.default.svc
  namespace: app
 syncPolicy:
  syncOptions:
   - CreateNamespace=true
  automated:
   selfHeal: true
   prune: true
